config/routes.rb
Rails.application.routes.draw do

  devise_for :users #John: What does this line do??

  root to: 'pages#home'

  resources :jets, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end
  namespace :user do
    resources :jets, only: %i[new create index show edit destroy update]
    resources :bookings, only: %i[index show destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :jet

  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date

  def booked_date_range
    { from: :start_date, to: :end_date }
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/models/jet.rb
class Jet < ApplicationRecord
  LOCATIONS = ["London", "Paris", "Rome"]
  PASSENGERS = [5, 10, 15]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :user, :model, :max_speed, :max_range, :price_hourly, :description, :fuel_consumption, :passenger_capacity, :location, presence: true

  has_one_attached :photo

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :jets, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!

include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @jet = Jet.find(params[:jet_id])
    @booking = Booking.new
    authorize @booking
  end

  def show
    @jet = Jet.find(params[:jet_id])
  end

  def create
    @jet = Jet.find(params[:jet_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.jet_id = params[:jet_id]
    authorize @booking
    if @booking.save
      redirect_to user_bookings_path
    else
      render :new
    end
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    @jets = policy_scope(Jet)
    if search_params_present?
      @passenger = search_params[:passenger]
      @location = search_params[:city]
      @jets = Jet.where(passenger_capacity: @passenger, location: @location).or(Jet.where(passenger_capacity: @passenger)).or(Jet.where(location: @location))
    end
  end

  def show
    @booking = Booking.new
  	@jet = Jet.find(params[:id])
    authorize @jet
  end

private

  def jet_params
    params.require(:jet).permit(:model, :max_speed, :max_range, :price_hourly, :fuel_consumption, :description)
  end

  def search_params
    params.permit(:passenger, :city)
  end

  def search_params_present?
    search_params.values.any?(&:present?)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/user/bookings_controller.rb
class User::BookingsController < ApplicationController
  def index
    # @bookings = Booking.where(user: current_user.id)
    @bookings = policy_scope([:user, Booking.where(user: current_user)])

  end

  def show
    @booking = Booking.find(params[:id])
    authorize [:user, @booking]
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize [:user, @booking]

    if @booking.destroy
      redirect_to user_bookings_path
    end
  end

  def booking_params
    params.require(:booking).permit(:duration, :date)
  end
end

app/controllers/user/jets_controller.rb
class User::JetsController < ApplicationController
  def index
    # @jets = Jet.where(user: current_user)
    @jets = policy_scope([:user, Jet.where(user: current_user)])
  end

  def show
    @jet = Jet.find(params[:id])
  end

  def new
    @jet = Jet.new
    authorize [:user, @jet]
  end

  def create
    @jet = Jet.new(jet_params)
    @jet.user = current_user
    authorize [:user, @jet]
    if @jet.save
      redirect_to user_jets_path
    else
      flash[:danger] = @jet.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @jet = Jet.find(params[:id])
    authorize @jet
  end

  def update
    @jet = Jet.find(params[:id])
    authorize [:user, @jet]

    if @jet.update(jet_params)
      redirect_to user_jets_path(@jet)
    end
  end

  def destroy
    @jet = Jet.find(params[:id])
    authorize [:user, @jet]

    if @jet.destroy
      redirect_to jets_path
    end
  end

  def jet_params
    params.require(:jet).permit(:model, :max_speed, :max_range, :price_hourly, :fuel_consumption, :description, :photo, :passenger_capacity, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Pick your time</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container bord text-center p-5">
  <h1>Please select date</h1>
  <div class="dates">
    <div class="form-inputs">
      <div class="form-row justify-content-center p-2">
        <%= simple_form_for([@jet, @booking]) do |f| %>
          <%= f.input :start_date, as: :string, label: "Date from", placeholder: "e.g. 22-02-2020", wrapper_html: { class: "inline_field_wrapper" } %>
          <%= f.input :end_date, as: :string, label: 'Date to'.html_safe, placeholder: "e.g. 22-02-2021", disabled: true, wrapper_html: { class: "inline_field_wrapper" } %>
          <%= f.submit "BOOK NOW", class: "btn btn-primary btn-block btn-booking" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="widget-content" data-unavailable="<%= @jet.unavailable_dates.to_json %>">
</div>
</div>

app/views/bookings/show.html.erb
show.html.erb

app/views/jets/index.html.erb
<div class="banner">
</div>
<div class="bottom d-flex justify-content-center align-items-center">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Private Jets Catalog</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
</div>
<div class="container mt-3">
    <%= simple_form_for "", method: :get, url: jets_path, wrapper: :inline_form,
  html: { class: "form-inline" },
  wrapper_mappings: {
    boolean: :inline_boolean
  } do |f| %>
      <%= f.label 'You can pick a city', class: "p-2" %>
      <%= f.input :city, label: "You can select city", placeholder_text: "please select city", collection: Jet::LOCATIONS, prompt: :translate, placeholder_text: "-- Select strands --" %>
      <div class="form-group row mb-0">
        <div class="col-sm-9 offset-sm-3">
      <%= f.submit value: "search", class: "btn btn-outline-secondary", style: "border-radius: 5px;" %>
      </div>
  </div>
    <% end %>
</div>
<div class="container mt-3">
  <div class="row justify-content-center">
    <% @jets.each do |jet| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 mb-4 spec">
      <div id="d" class="card text" style="width: 16rem; height: 19rem;">
        <% if jet.photo.attached? %>
        <%= cl_image_tag jet.photo.key, width: 600, height: 200, crop: :fit, class: "hover" %>
        <% else %>
        <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn-image.departures.com%2Fsites%2Fdefault%2Ffiles%2F1572446921%2Fheader-general-private-jet-on-tarmac-BESTJETCOMP1019.jpg&imgrefurl=https%3A%2F%2Fwww.departures.com%2Ftravel%2Ftop-private-jet-companies-to-know&tbnid=TTpAbWa5oorIZM&vet=12ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ..i&docid=DLeHzjzHiNI-bM&w=2000&h=1333&q=private%20jet%20plane&ved=2ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ" />
        <% end %>
        <div class="card-body">
          <h5 class="card-title" ><%= jet.model %></h5>
        </div>
      </div>
      <div class="triangle-right">
      </div>
      <div>
        <%= link_to "Learn More", jet_path(jet), class: "btn btn-primary more" %>
        <% link_to '',  jet_path(jet), :class => "stretched-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "www.yoursite.com";
    };
</script>

app/views/jets/show.html.erb
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5"><%= @jet.model.truncate_words(1)%></h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container m-5">
    <div class="row">
      <div class="col-8">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% if @jet.photo.attached? %>
              <%= cl_image_tag @jet.photo.key, width: 700, height: 550, crop: :fit %>
              <% else %>
              <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn-image.departures.com%2Fsites%2Fdefault%2Ffiles%2F1572446921%2Fheader-general-private-jet-on-tarmac-BESTJETCOMP1019.jpg&imgrefurl=https%3A%2F%2Fwww.departures.com%2Ftravel%2Ftop-private-jet-companies-to-know&tbnid=TTpAbWa5oorIZM&vet=12ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ..i&docid=DLeHzjzHiNI-bM&w=2000&h=1333&q=private%20jet%20plane&ved=2ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ" />
              <% end %>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://res.cloudinary.com/dd0q8x2lk/image/upload/v1601563779/fs_Pilatus-Aircraft-Ltd-PC-24-cabin-03_gzaqh8.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://res.cloudinary.com/dd0q8x2lk/image/upload/v1601564102/72768789224809867e5df20d1fdf4fe8_anohte.png" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    <div class="col-4">
      <div class="card-bo text-xs-left">
        <h1><%= @jet.model %></h1>
        <h2>
          <p><strong>Max speed:</strong><br><%= @jet.max_speed %><em>km/h</em></p>
          <p><strong>Max range:</strong><br><%= @jet.max_range%><em>km</em></p>
          <p><strong>Price hourly:</strong><br><%= @jet.price_hourly%><em>$</em></p>
          <p><strong>Passenger capacity:</strong><em>  <%= @jet.passenger_capacity%></em></p>
          <p><strong>Description:</strong><br><%= @jet.description%></p>
        </h2>
    </div>
      <div class="book">
        <%= link_to "BOOK NOW", new_jet_booking_path(@jet), class: "btn btn-primary mb-n3" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JetNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

    <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <div class="page-container">
        <div class="page-content">
          <%= render 'shared/navbar' %>
          <%= render 'shared/flashes' %>
          <%= yield %>
        </div>
        <div class="page-footer">
          <%= render 'shared/footer' %>
        </div>
      </div>
    </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid p-0 hero-banner">
  <%= image_tag("hero-image.jpg", class: "hero-image")%>
</div>
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Pick your jet</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container py-5">
  <div class="text-center">
      <h3>Private Jet Rental Services Worldwide</h3>
      <p>Choose your aircraft you’d like to book and complete the reservation online, simple as that!</p>
      <%= link_to 'Search Jets', jets_path, class: 'btn btn-primary' %>
    </div>

<div class="container mt-5">
 <div class="row justify-content-between" style="margin-right: 45px;">
      <div class="col-xs-12 col-sm-6 col-lg-3 mb-4  text-center">
        <div class="cards" style="width: 18rem; height: 19rem;">
          <i class="fas fa-plane-departure"></i>
          <div class="card-b">
          	<h1 class="cards-title">Services</h1>
          </div>
          <div class="card-description">
        		<p>Online booking 24/7, no minimum notice, free cancellations.</p>
        </div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-lg-3 mb-4">
        <div class="cards" style="width: 18rem; height: 19rem;">
        	<i class="fas fa-award"></i>
        	<div class="card-b">
          <h1 class="cards-title">Flexibility</h1>
        </div>
        <div class="card-description">
        	<p>Choose business, leisure or cargo charters</p>
        </div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-lg-3 mb-4">
        <div class="cards" style="width: 18rem; height: 19rem;">
        	 <i class="fas fa-handshake"></i>
        	  <div class="card-b">
          		<h1 class="cards-title">Connect</h1>
        		 </div>
        		<div class="card-description">
        			<p>We are connecting people.Benefit from the market neutrality.</p>
        </div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-fluid padding">
    <div class="row text-center d-flex justify-content-center">
      <div class="col-sm-12 col-md-8 d-flex align-items-baseline justify-content-around">
        <img class="footer-icon" src="https://www.huntandpalmer.com/wp-content/uploads/2014/08/ebaa_wht_new2-108x39.png" alt="">
        <img class="footer-icon" src="https://assets.privatefly.com/images/general/bbc.png">
        <img class="footer-icon" src="https://s3-eu-west-1.amazonaws.com/assets.privatefly.com/images/icons/Virtuoso_Preferred_120.png">
        <img class="footer-icon" src="https://assets.privatefly.com/images/general/bbusiness.png">
        <img class="footer-icon" src="https://s3-eu-west-1.amazonaws.com/assets.privatefly.com/images/icons/Air-Charter-Association-logo_120px.png">


      </div>
      <div class="col-12">
        <hr class="light">
        <p class="footer-small-text"><span>&copy; JET NOW 2005-2020</span> | ABOUT | <span>CONTACT US</span> | PRIVACY | SITEMAP  |  <span>CORP. RESPONSIBILITY</span></P>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("JetNow_logo.png", class: "JetNow_logo") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Jets", jets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rent my jet", new_user_jet_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.iconfinder.com/data/icons/user-interface-151/24/List_menu_toggle-512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings", user_bookings_path, class: "dropdown-item" %>
            <%= link_to "My jets", user_jets_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item danger" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user/bookings/index.html.erb
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Bookings</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container text-dark mb-5">
  <% if @bookings.count == 0 %>
    <div class="no-jets d-flex pl-3 pr-3 pb-5">
      <div class="row">
        <div class="col-12 text-center">
          <h4 class="mt-5 d">You <head></head>have no bookings yet<span>...</span></h4>
        </div>
        <div class="col-12 d-flex justify-content-center">
          <%= link_to 'Book a Jet', jets_path, :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="yes-jets">
     <h1 class="text-center mb-5">Your Bookings</h1>
     <div class="container">
      <div class="row d-flex justify-content-center">
        <% @bookings.each do |b| %>
          <div class="col-xs-12 col-lg-6 d-flex justify-content-center">
            <div class="card-product d-flex border mb-3">
             <% if b.jet.photo.attached? %>
                <%= cl_image_tag b.jet.photo.key %>
              <% else %>
                <img src="https://w7.pngwing.com/pngs/1006/271/png-transparent-airplane-aircraft-flight-computer-icons-private-jet-angle-airplane-flight-thumbnail.png" />
              <% end %>
              <div class="card-product-infos">
                <h2><%= b.jet.model %> <span class="divider">|</span> <span class="location"> <%= b.jet.location %> </span></h2>
                <ul class="list-unstyled">
                  <li> Starts: <%= b.start_date %> </li>
                  <%= link_to '',  user_booking_path(b), :class => "stretched-link" %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/user/bookings/show.html.erb
<div class="container m-5">
   <div class="row">
      <div class="col-8">
      <% if @booking.jet.photo.attached? %>
      <%= cl_image_tag @booking.jet.photo.key, width: 700, height: 550, crop: :fit %>
      <% else %>
      <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn-image.departures.com%2Fsites%2Fdefault%2Ffiles%2F1572446921%2Fheader-general-private-jet-on-tarmac-BESTJETCOMP1019.jpg&imgrefurl=https%3A%2F%2Fwww.departures.com%2Ftravel%2Ftop-private-jet-companies-to-know&tbnid=TTpAbWa5oorIZM&vet=12ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ..i&docid=DLeHzjzHiNI-bM&w=2000&h=1333&q=private%20jet%20plane&ved=2ahUKEwj63pTjhJHsAhWigM4BHcUDDfkQMygBegUIARDWAQ" />
      <% end %>
    </div>
    <div class="col-4">
      <div class="card-bo text-xs-left">
      <h1><% @booking.user %></h1>
        <h2><strong><%= @booking.jet.model %></strong></h2><br>
          <h3>
          <p><strong> Jet location :</strong><em><%= @booking.jet.location %></em></p>
          <p><strong> Jet capacity :</strong><em><%= @booking.jet.passenger_capacity %></em></p>
          <p><strong> Booking ID :</strong><em><%= @booking.jet_id %></em></p>
          <p><strong> Booking start date :</strong><br><em><%= @booking.start_date %></em></p>
          <p><strong> Booking end date :</strong><br><em><%= @booking.end_date %></em></p>
          <p><strong> Description :</strong><br><em><%= @booking.jet.description %></em></p>
        </h3>
          <div class="cancel d-flex justify-content-end">
     <%= link_to "CANCEL", user_booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary mb-n3" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/user/jets/edit.html.erb
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Changes</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container bord">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="m-3">Edit your jet details</h1>
        <%= simple_form_for [:user, @jet] do |f| %>
          <%= f.error_notification %>
          <%= f.input :model, class: "form-control font-weight-bold"%>
          <div class="row">
            <div class="col-6">
              <%= f.input :price_hourly, label: "Price hourly $", placeholder: "e.g. 190$" %>
            </div>
            <div class="col-6">
              <%= f.input :max_speed, label: "Maximum speed", placeholder: "e.g. 900km/h" %>
            </div>
          </div>
          <div class="row">
            <div class="col-4">
              <%= f.input :passenger_capacity, label: "capacity", placeholder: "e.g. 15 seats", collection: Jet::PASSENGERS, prompt: :translate %>
            </div>
            <div class="col-4">
               <%= f.input :max_range, label: "Range", placeholder: "e.g. 3000km" %>
            </div>
            <div class="col-4">
              <%= f.input :fuel_consumption, label: "Consumption", placeholder: "e.g. 25l/km" %>
            </div>
          </div>
            <%= f.input :location, collection: Jet::LOCATIONS, prompt: :translate %>
            <%= f.input :photo, as: :file %>
            <%= f.input :description, label: "Description about the jet", placeholder: "e.g. Very nice and cosy jet, also very fast and quiet" %>
          <div class="d-flex inline-block justify-content-center align-items-center">
            <div class="m-2">
            <%= f.button :submit, class: "btn btn-success  btn-block" %>
            </div>
            <div>
            <%= link_to "Remove my jet", user_jet_path(@jet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger m-2" %>
            </div>
          </div>
          <% end %>
    </div>
  </div>
</div>

app/views/user/jets/index.html.erb
<div class="bottom d-flex justify-content-center align-items-center mb-5">
  <div style="margin-right: 50px;">
    <h3 class="display-5">Catalog</h3>
  </div>
  <div>
    <hr>
  </div>
</div>
<div class="container text-dark mb-5">
  <% if @jets.count == 0 %>
    <div class="no-jets d-flex pl-3 pr-3 pb-5">
      <div class="row">
        <div class="col-12 text-center">
          <h4 class="mt-5">You do not have any jets yet<span>...</span></h4>
        </div>
        <div class="col-12 d-flex justify-content-center">
          <%= link_to 'Add a Jet', new_user_jet_path, :class => "btn btn-primary" %>
        </div>
      </div>
  <% else %>
    <div class="yes-jets">
     <h1 class="text-center mb-5">Your Jets</h1>
     <div class="container">
      <div class="row d-flex justify-content-center">
        <% @jets.each do |j| %>
          <div class="col-xs-12 col-lg-6 d-flex justify-content-center">
            <div class="card-product d-flex border mb-3">
             <% if j.photo.attached? %>
                <%= cl_image_tag j.photo.key %>
              <% else %>
                <img src="https://w7.pngwing.com/pngs/1006/271/png-transparent-airplane-aircraft-flight-computer-icons-private-jet-angle-airplane-flight-thumbnail.png" />
              <% end %>
              <div class="card-product-infos">
                <h2><%= j.model %> <span class="divider">|</span> <span class="location"> <%= j.location %> </span></h2>
                <ul class="list-unstyled">
                  <li> Max Passengers: <%= j.passenger_capacity %> </li>
                  <li> Max Speed: <%= j.max_speed %> km/hr</li>
                  <%= link_to '',  edit_user_jet_path(j), :class => "stretched-link" %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>


<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "www.yoursite.com";
    };
</script>